version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      all-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "cargo"
    directory: "/rage-webassembly"
    schedule:
      interval: "weekly"
    groups:
      all-dependencies:
        patterns:
          - "*"
