version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      all-dependencies-npm:
        patterns:
          - "*"

  - package-ecosystem: "cargo"
    directory: "/rage-webassembly"
    schedule:
      interval: "monthly"
    groups:
      all-dependencies-cargo:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      all-dependencies-actions:
        patterns:
          - "*"
