name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.7
      - uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: "latest"

      - name: Build Subproject
        run: |
          cd rage-webassembly
          cargo test
          wasm-pack build

      - name: Build Main Project
        run: |
          pnpm install
          pnpm lint
          pnpm check
